<?php
$enable = Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart');
?>
<?php $_cartQty = $this->getSummaryCount() ?>
<div class="mt-maincart">
    <span class="mt-cart-loading">Loading...</span>
    <div class="mt-cart">
        <div class="mt-icon-ajaxcart">
            <div class="mt-icon icon-cart ">
                <a class="mt-cart-label" href="<?php echo $this->getUrl('checkout/cart') ?>">
                    <span class="fa fa-shopping-cart"></span>
                    <span class="cart-qty"><?php echo $_cartQty == 0 ? '0' : $_cartQty; ?><span class="last-fix"> items</span></span>
                </a>
            </div>
            <!--                        <span class="print" style="clear:both;display: block;">
                           <span class="cart-txt"><?php /*echo $this->__('My cart') */ ?></span>
                            <?php /*echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) */ ?>
                        </span>-->
        </div>
        <div class="ajaxcart">
            <div class="search-form-border"></div>
            <div class="mt-ajax-container">
                <?php
                $_items = $this->getRecentItems($_cartQty);
                if (count($_items)):
                    ?>
                    <ul class="clearfix">
                        <?php foreach ($_items as $_item): ?>
                            <?php echo $this->getItemHtml($_item) ?>
                        <?php endforeach; ?>
                    </ul>
                    <p class="subtotal">
                        <?php if ($this->canApplyMsrp()): ?>
                            <span
                                class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                        <?php else: ?>
                            <span
                                class="label"><?php echo $this->__('Total:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                            <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                                <br/>(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?><?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                            <?php endif; ?>
                        <?php endif; ?>
                    </p>
                    <div class="mt-ajax-checkout">
                        <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="view-cart">
                            <span><?php echo $this->__('View cart') ?></span>
                        </a>
                        <?php if (Mage::getStoreConfig('opc/global/status')) { ?>
                            <a href="<?php echo $this->getUrl('onepage') ?>"><span><?php echo $this->__('Checkout') ?></span></a>
                        <?php } else { ?>
                            <a href="<?php echo $this->getCheckoutUrl() ?>"><span><?php echo $this->__('Checkout') ?></span></a>
                        <?php } ?>
                    </div>
                <?php else: ?>
                    <p class="no-items-in-cart"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>
<div id="notification"></div>
<div style="display: none">
    <div id="inline">
        <div class="cart-ajax-title"></div>
        <div
            class="add-cart-notice"><?php echo $this->__('The product quantity has been updated'); ?></div>
        <div class="action mt-ajax-checkout">
            <button class="continue button" onclick="$mt.colorbox.close();">
                <span><?php echo $this->__('Continue shopping'); ?></span>
            </button>
            <a class="show-cart"
               href="<?php echo $this->getUrl('checkout/cart') ?>"><span><?php echo $this->__('Show cart'); ?></span></a>
        </div>
    </div>
</div>
<script type="text/javascript">
    var datatext = {};
    datatext.load = '<?php echo $this->__('processing');?>';
</script>