<?php
/**
 * @category    MT
 * @package     MT_Widget
 * Copyright (C) 2008-2015 ZooExtension.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author ZooExtension.com
 * @email       magento@cleversoft.co
 */
?>
<?php
$blocks     = $this->getBlocks();
$id         = $this->getConfig('id');
$scroll     = $this->getConfig('scroll');
$title      = $this->getConfig('widget_title');
?>
<div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $id ?>">
		<div class="block block-sample row clearfix">
		    <?php if ($title): ?>
		    <div class="block-title">
				<strong><span><?php echo $title ?></span></strong>
			</div>
			<?php endif ?>
			 <div class="<?php echo $scroll==1 ? 'owl-carousel ' : '' ?>">
				<?php foreach ($blocks as $block): ?>
					<div class="<?php echo $scroll==1 ? 'block-content' : $block['class']?>">
						<?php echo $block['content'] ?>
					</div>
				<?php endforeach ?>
			</div>
		</div>
	<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>mt/widget/frontend.js"></script>
    <script type="text/javascript">
        new MT.Widget('<?php echo $id ?>', {
            animation: <?php echo $this->getConfig('animation') ?>,
            parallax: <?php echo $this->getConfig('parallax') ?>,
            carousel: <?php echo $this->getConfig('carousel') ?>,
            carouselConfig: null,
            kenburns: <?php echo $this->getConfig('kenburns') ?>,
            onRefresh: true,
            onLazyload: false,
            autoHeight: false
        });
    </script>
</div>
