<?php
/**
 * @category    MT
 * @package     MT_Widget
 * Copyright (C) 2008-2015 ZooExtension.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author ZooExtension.com
 * @email       magento@cleversoft.co
 */
?>
<?php
$_id                = $this->getConfig('id');
$_title             = $this->getConfig('widget_title');
$t                  = microtime();
?>

    <div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $_id ?>">
        <div class="main-heading">
            <div class="heading-wrapper-title">
                <?php if ($_title): ?>
                    <h3><span><?php echo $_title ?></span></h3>
                <?php endif ?>
            </div>
        </div>
		<?php echo $this->renderCollection('collection', $this->getData('mode'), 'mt/widget/collection/collection_positionright_detail.phtml') ?>
    </div>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>mt/widget/frontend.js"></script>
    <script type="text/javascript">
        new MT.Widget('<?php echo $_id ?>', {
            animation: <?php echo $this->getConfig('animation') ?>,
            parallax: <?php echo $this->getConfig('parallax') ?>,
            carousel: <?php echo $this->getConfig('carousel') ?>
        });
    </script>

<?php //Mage::log(microtime() - $t) ?>
