<?php
/**
 * @category    MT
 * @package     MT_Widget
 * Copyright (C) 2008-2015 ZooExtension.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author ZooExtension.com
 * @email       magento@cleversoft.co
 */
?>
<?php
/* @var $this MT_Widget_Block_Widget */
$id         = $this->getConfig('id');
$title      = $this->getConfig('widget_title');
$tabs       = $this->getTabs();
$cats       = $this->getCatTabs();


$template   = 'mt/widget/collection/collection.phtml';
$t          = microtime();
?>
<div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $id ?>">
    <div class="tabs-collection">
        <div class="main-heading">
            <div class="heading-wrapper-title">
            <?php if ($title): ?>
                <h3><span><?php echo $title ?></span></h3>
            <?php endif ?>
             </div>
         </div>
	
        <a class="toggle-tab" style="display:none;">
            <span class="stick-txt"></span>
            <span class="stick-notxt">
                <span class="icon-toggle"></span>
                <span class="icon-toggle"></span>
                <span class="icon-toggle"></span>
            </span>
           <span class="all-collect">All Collection</span>
        </a>
        <ul class="widget-tabs nav nav-tabs">
            <?php foreach ($tabs as $index => $tab): ?>
                <li class="<?php echo $index==0 ? 'active' : '' ?>">
                    <a href="#<?php echo $id . '-' . $tab['id'] ?>"
                        data-value="<?php echo $tab['value'] ?>"
                        data-type="<?php echo $tab['type'] ?>"
                        data-limit="<?php echo $this->getLimit() ?>"
                        data-column="<?php echo $this->getConfig('column') ?>"
                        data-loadmore="<?php echo $this->getData('show_loadmore') ?>"
                        data-numloadmore="<?php echo $this->getData('num_loadmore') ?>"
                        data-row="<?php echo $this->getConfig('row') ?>"
                        data-showfilter="<?php echo $this->getConfig('show_filter') ?>"
                        data-cid="<?php echo $this->getData('category_ids') ?>"
                        data-template="<?php echo $template ?>"
                        data-carousel="<?php echo $this->getConfig('scroll') ?>">
                        <?php echo $tab['label'] ?>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
        <?php if($this->getConfig('show_filter')): ?>
        <ul class="filter-tabs nav nav-tabs">
            <li class="">
                <a href="#<?php echo $id . '-' . $tabs[0]['id'] ?> .widget-filter" class="filter" ><?php echo Mage::helper('core')->__('Filter'); ?></a>
            </li>
        </ul>
        <?php endif; ?>
        <?php if(count($cats) > 0) :?>
            <ul class="widget-tabs-cats nav nav-tabs" style="margin-right: 322px;">
                <?php foreach ($cats as $i => $cat): ?>
                    <li class="<?php echo $i==0 ? 'active' : '' ?>">
                        <a class="" href="#"
                           data-cid="<?php echo $cat['value'] ?>"
                           data-type="<?php echo $cat['type'] ?>"
                           data-limit="<?php echo $this->getLimit() ?>"
                           data-loadmore="<?php echo $this->getData('show_loadmore') ?>"
                           data-numloadmore="<?php echo $this->getData('num_loadmore') ?>"
                           data-column="<?php echo $this->getConfig('column') ?>"
                           data-template="<?php echo $template ?>"
                           data-carousel="<?php echo $this->getConfig('scroll') ?>">
                            <?php echo $cat['label'] ?>
                        </a>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php endif;?>
    </div>
    <div class="widget-tab-content tab-content">
        <?php foreach ($tabs as $index => $tab): ?>
            <div id="<?php echo $id . '-' . $tab['id'] ?>" class="tab-pane<?php echo $index==0 ? ' active' : '' ?>">
                <?php if ($index > 0): ?>
                    </div>
                    <?php continue ?>
                <?php endif ?>
                <?php if(count($cats) > 0) :?>
                    <?php echo $this->renderTabCollection($cats[0]['value'], $tab['value'], $template) ?>
                <?php else :?>
                    <?php echo $this->getConfig('show_filter') ? $this->renderFilterCollection($tab['value']) : '' ?>
                    <?php echo $this->renderCollection($tab['type'], $tab['value'], $template) ?>
                <?php endif;?>
            </div>
        <?php endforeach ?>
    </div>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>mt/widget/frontend.js"></script>
    <script type="text/javascript">
        new MT.Widget('<?php echo $id ?>', {
            animation: <?php echo $this->getConfig('animation') ?>,
            collectionUrl: '<?php echo $this->getUrl('mtwidget/collection/get') ?>',
            collectionLoadmore: '<?php echo $this->getUrl('mtwidget/collection/loadmore') ?>',
            collectionCallback: function(){},
			showFilter : '<?php echo $this->getConfig('show_filter');?>',
            spinnerClass: 'spinner',
            spinnerImg: '<?php echo $this->getSkinUrl('css/magenthemes/cloudzoom/images/loading.gif') ?>',
            parallax: <?php echo $this->getConfig('parallax') ?>,
            carousel: <?php echo $this->getConfig('carousel') ?>,
            carouselConfig: null,
            countdown: <?php echo $this->getConfig('countdown') ?>,
            countdownConfig: null,
            kenburns: <?php echo $this->getConfig('kenburns') ?>
        });
    </script>
</div>

<?php //Mage::log(microtime() - $t) ?>
