<?php
/**
 * @category    MT
 * @package     MT_Filter
 * @copyright   Copyright (C) 2008-2015 ZooExtension.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author ZooExtension.com
 * @email       magento@cleversoft.co
 */
?>
<?php
    $bar = Mage::helper('mtfilter')->getConfig('mtfilter/general/bar');
    $barColor = '#'.Mage::helper('mtfilter')->getConfig('mtfilter/general/bar_color');
?>
<div id="<?php echo $this->getHash()?>" class="price-slider">
    <div id="<?php echo $this->getHash('-min')?>" class="price-slider-handle min"></div>
    <div id="<?php echo $this->getHash('-max')?>" class="price-slider-handle max"></div>
    <div id="<?php echo $this->getHash('-span')?>" class="price-slider-span"></div>
</div>
<div class="layer-price">
    <?php echo $this->getCurrencySymbol()?><span id="layer-price-min"></span>&nbsp;&nbsp;-&nbsp;&nbsp;<?php echo $this->getCurrencySymbol()?><span id="layer-price-max"></span>
</div>
<style type="text/css">
    .price-slider{
        height: 8px;
        width: 86%;
        background: #ececec;
        position: relative;
        margin: 10px auto;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }
    .price-slider .price-slider-handle{
		height: 16px;
		position: absolute;
		top: -4px;
		width: 16px;
    }
    .price-slider-handle.min{
        background: #484848;
    }
    .price-slider-handle.max{
        background: #d33f37;
    }
    .layer-price{
        text-align: center;
    }
</style>
<script type="text/javascript">
    window.mtFilter.initPriceFilter(<?php echo $this->getConfig()?>);
</script>